name: Mirror

on:
  schedule:
    - cron: '10 17 * * *'
  
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Configure environment
      run: |
        git config --global user.name GitHub_Action
        git checkout -b temp

    - name: Install Dependencies
      run: |
        git clone https://github.com/YYF233333/mirrorsite.git
        python3 -m pip install -r mirrorsite/requirements.txt
    
    - name: Download release
      uses: robinraju/release-downloader@v1.3
      with: 
        repository: "YYF233333/mirrorsite"
        latest: true
        fileName: "mirrorsite"
        # Download the attached tarball (*.tar.gz)
        tarBall: false
        # Download the attached zipball (*.zip)
        zipBall: false
        out-file-path: "mirrorsite"

    - name: Cloning and Mirroring site
      run: |
        mv icourse.club mirrorsite/icourse.club
        cd mirrorsite
        chmod +x ./mirrorsite
        python3 ./mirror_site.py --min=1 --max=150
        mv icourse.club ../icourse.club
    
    - name: Commit and push changes
      run: |
        git add .
        git commit -m "Scheduled update (page1-150)"
        git push origin temp:temp
