name: Mirror2

on:
  workflow_run:
    workflows: [Mirror]
    types: [completed]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - uses: actions/checkout@v3
      with:
        ref: temp
    
    - name: Configure environment
      run: |
        git config --global user.name GitHub_Action
        git checkout temp

    - name: Install Dependencies
      run: |
        git clone https://github.com/YYF233333/mirrorsite.git
        gh release download --repo YYF233333/mirrorsite -p "mirrorsite" --dir ./mirrorsite
        python3 -m pip install -r requirements.txt

    - name: Cloning and Mirroring site
      run: |
        mv icourse.club mirrorsite/icourse.club
        cd mirrorsite
        python3 ./mirror_site.py --min=1 --max=150 --convert-links --convert-images
        mv icourse.club ../icourse.club
              
    - name: Commit and push changes
      run: |
        git add .
        git commit -m "Scheduled update (page151-300)"
        git push origin temp
