name: Mirror2

on:
  workflow_run:
    workflows: [Mirror]
    types: [completed]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - uses: actions/checkout@v3
      with:
        ref: temp
    
    - name: Configure environment
      run: |
        git config --global user.name GitHub_Action
        git checkout temp

    - name: Install Dependencies
      run: python3 -m pip install -r requirements.txt

    - name: Cloning and Mirroring site
      run: python3 ./mirror_site.py --min=101 --max=200
        
    - name: Commit and push changes
      run: |
        git add .
        git commit -m "Scheduled update (page101-200)"
        git push origin temp
