name: Release

on:
  workflow_run:
    workflows: [Finish]
    types: [completed]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Configure environment
      run: git config --global user.name GitHub_Action
    
    - name: Build release
      run: |
        sudo apt install p7zip
        7z a -t7z -mx=9 "release/`echo $(date -I -u)`.7z" ./icourse.club/
    
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
    
    - name: Create release
      uses: xresloader/upload-to-github-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        file: "release/*"
        draft: false
        tag_name: "daily-update-${{ steps.date.outputs.date }}"
